# Generated by Django 4.2 on 2023-04-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0008_passport'),
        ('applicationsapp', '0003_remove_application_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='infoapp.passport'),
            preserve_default=False,
        ),
    ]
