# Generated by Django 4.2 on 2023-06-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationsapp', '0011_application_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_payment',
        ),
    ]
