# Generated by Django 4.2 on 2023-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationsapp', '0012_remove_application_is_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='kvitansiya_upload',
            field=models.FileField(blank=True, null=True, upload_to='kvitansiyalar'),
        ),
    ]
