# Generated by Django 4.2 on 2023-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
