# Generated by Django 4.2 on 2023-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userverification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_perevod',
            field=models.BooleanField(default=False),
        ),
    ]
