# Generated by Django 4.2 on 2023-05-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_perevod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_perevod',
        ),
    ]
