# Generated by Django 4.2 on 2023-05-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requiredapp', '0003_passportfuqaroligi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talimshakli',
            options={'ordering': ['-id'], 'verbose_name_plural': "Ta'lim shakllari"},
        ),
    ]
