# Generated by Django 4.2 on 2023-06-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requiredapp', '0004_alter_talimshakli_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talimyonalishi',
            name='talim_turi',
        ),
    ]
