# Generated by Django 4.2 on 2023-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images/ui')),
                ('image_2', models.ImageField(upload_to='images/ui')),
                ('image_3', models.ImageField(upload_to='images/ui')),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('what', models.CharField(max_length=255)),
                ('what_body', models.CharField(max_length=255)),
                ('button_href', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=455)),
                ('button_title', models.CharField(max_length=255)),
                ('button_href', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_href', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/ui')),
            ],
        ),
        migrations.CreateModel(
            name='Litsenziya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_href', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/ui')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
                ('site_title', models.TextField()),
                ('author', models.TextField()),
                ('logo', models.ImageField(upload_to='images/ui')),
                ('favicon', models.ImageField(upload_to='images/ui')),
                ('phone_1', models.CharField(max_length=255)),
                ('phone_2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='TalimYonalishlariSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ui')),
                ('title', models.CharField(max_length=255)),
                ('p1', models.CharField(max_length=255)),
                ('p2', models.CharField(max_length=255)),
                ('button_href', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ui')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
