# Generated by Django 4.2 on 2023-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='right_text',
            field=models.TextField(max_length=455, null=True),
        ),
    ]
