# Generated by Django 4.2 on 2023-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0003_alter_sitesettings_right_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='background_image',
            field=models.ImageField(null=True, upload_to='images/ui'),
        ),
    ]
