# Generated by Django 4.2 on 2023-05-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0005_homesection_button_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='button_image',
        ),
    ]
