# Generated by Django 4.2 on 2023-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0007_alter_facultet_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultet',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
