# Generated by Django 4.2 on 2023-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0009_facultet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
