# Generated by Django 4.2 on 2023-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0010_video_subtitle_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/ui'),
        ),
    ]
