# Generated by Django 4.2 on 2023-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
