# Generated by Django 4.2 on 2023-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_alter_passport_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_series',
            field=models.CharField(max_length=9),
        ),
    ]
