# Generated by Django 4.2 on 2023-04-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoapp', '0003_alter_passport_passport_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='abituriyent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
