# Generated by Django 4.2 on 2023-04-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoapp', '0004_passport_abituriyent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot_turi', models.CharField(max_length=255)),
                ('muassasa_turi', models.CharField(max_length=255)),
                ('muassasa_nomi', models.TextField()),
                ('tugatgan_yili', models.CharField(max_length=255)),
                ('tugatgan_muassasa_joylashgan_viloyat', models.CharField(max_length=255)),
                ('tugatgan_muassasa_joylashgan_tuman', models.CharField(max_length=255)),
                ('diplom_file', models.FileField(upload_to='files/diplomlar/')),
                ('tavsiyanoma_file', models.FileField(upload_to='files/tavsiyanomalar/')),
                ('mehnat_daftarcha_file', models.FileField(blank=True, null=True, upload_to='files/mehnat_daftarcha/')),
                ('xalqaro_sertifikat_file', models.FileField(blank=True, null=True, upload_to='files/tavsiyanomalar/')),
                ('diplom_seriya', models.CharField(max_length=255)),
                ('abituriyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('abituriyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
