# Generated by Django 4.2 on 2023-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0005_diplom_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='abituriyent',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='passport_file',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='passport_jshshir',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='place_of_birth',
        ),
    ]
