# Generated by Django 4.2 on 2023-04-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationsapp', '0003_remove_application_passport'),
        ('infoapp', '0006_remove_passport_abituriyent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
