# Generated by Django 4.2 on 2023-04-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoapp', '0007_delete_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('fuqaroligi', models.CharField(max_length=255)),
                ('nation', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('viloyat', models.CharField(max_length=255)),
                ('tuman', models.CharField(max_length=255)),
                ('manzil', models.TextField()),
                ('kim_tomonidan_berilgan', models.TextField()),
                ('passport_series', models.CharField(max_length=9)),
                ('passport_jshshir', models.CharField(max_length=14)),
                ('passport_file', models.FileField(upload_to='files/passports/')),
                ('abituriyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
