# Generated by Django 4.2 on 2023-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0008_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='kim_tomonidan_berilgan',
            field=models.CharField(max_length=555),
        ),
    ]
