# Generated by Django 4.2 on 2023-05-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationsapp', '0005_remove_application_contact'),
        ('infoapp', '0009_alter_passport_kim_tomonidan_berilgan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
