# Generated by Django 4.2 on 2023-05-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0010_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplom',
            options={'verbose_name_plural': 'Diplomlar'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name_plural': 'Pasportlar'},
        ),
    ]
