# Generated by Django 4.2 on 2023-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0011_alter_diplom_options_alter_passport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerevodDiplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat', models.CharField(max_length=455)),
                ('unv_nomi', models.CharField(max_length=555)),
                ('file', models.FileField(upload_to='perevod/')),
                ('kurs', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Perevod diplomlari',
            },
        ),
    ]
