# Generated by Django 4.2 on 2023-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0012_perevoddiplom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplom',
            name='mehnat_daftarcha_file',
        ),
        migrations.RemoveField(
            model_name='diplom',
            name='tavsiyanoma_file',
        ),
    ]
