# Generated by Django 4.2 on 2023-05-28 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoapp', '0013_remove_diplom_mehnat_daftarcha_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevoddiplom',
            name='abituriyent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
